# Generated by Django 4.2.4 on 2023-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
