# Generated by Django 4.2.4 on 2023-08-06 18:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name="images"),
        ),
    ]
