# Generated by Django 4.2.4 on 2023-08-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
