/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * doshro_bazar API
 * Documentation of API endpoints of doshro_bazar
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface PaginatedUserList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: User[];
}
