/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * doshro_bazar API
 * Documentation of API endpoints of doshro_bazar
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaRetrieveFormat } from './schemaRetrieveFormat';
import type { SchemaRetrieveLang } from './schemaRetrieveLang';

export type SchemaRetrieveParams = {
format?: SchemaRetrieveFormat;
lang?: SchemaRetrieveLang;
};
