# Generated by Django 4.2.4 on 2023-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listings_views_alter_listingviews_listing_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="is_featured",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="listings",
            name="is_scraped",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="listings",
            name="link_to_original",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
