# Generated by Django 4.2.4 on 2023-12-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_listings_is_featured_listings_is_scraped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="banner_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
