# Generated by Django 4.2.4 on 2024-01-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_listings_is_negotiable_listings_is_sfw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="scraped_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="listings",
            name="scraped_views",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
