/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * doshro_bazar API
 * Documentation of API endpoints of doshro_bazar
 * OpenAPI spec version: 1.0.0
 */
import { rest } from 'msw';
import { faker } from '@faker-js/faker';

export const getSchemaRetrieveMock = () =>
  faker.helpers.arrayElement([
    {
      cll9gqiwm0000zkub6tep6jyr: {},
    },
    {
      cll9gqiwn0001zkubara8agpa: {},
    },
    {
      cll9gqiwn0002zkubaedrcf3x: {},
    },
    {
      cll9gqiwn0003zkub6tahcsju: {},
    },
  ]);

export const getSchemaMSW = () => [
  rest.get('*/api/schema/', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getSchemaRetrieveMock()),
    );
  }),
];
