import Head from 'next/head';
import { initializeStore, useStore } from '../../components/store/store';
import { ReactElement, useEffect } from 'react';
import { QueryClient, dehydrate } from '@tanstack/react-query';
import { NextPageContext } from 'next';
import { getDefaultStore } from '../../components/utils/PageDefaults';
import MainLayout from '../../components/layouts/MainLayout';

export async function getServerSideProps(ctx: NextPageContext) {
  const queryClient = new QueryClient();
  const zustandStore = await getDefaultStore(ctx);
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      initialZustandState: JSON.parse(JSON.stringify(zustandStore)),
    },
  };
}

Home.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;

export default function Home() {
  const store = useStore((state) => state.accessToken);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello this is me</h1>
    </>
  );
}
