# Generated by Django 4.2.4 on 2023-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="id_from_api",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
