name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    env:
      #Skipping as this is already done on another job
      SKIP: frontend-test-runner,prettier
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  # With no caching at all the entire ci process takes 4m 30s to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Create empty env
        run: |
          touch .envs/.local/.django
          echo USE_DOCKER=yes >> .envs/.local/.django
          echo REDIS_URL=redis://redis:6379/0 >> .envs/.local/.django
          echo CELERY_FLOWER_USER=pOrKBvglpnlYTRfAhlWVTZwjdoiKAhYN >> .envs/.local/.django
          echo CELERY_FLOWER_PASSWORD=SnL85PQVgfSgvLYamAKSmyj97f5CI2e82t2fTWIv1sEDUeENrIwJvUhi6uxzWYdJ >> .envs/.local/.django
          cat .envs/.local/.django

      - name: Build the Stack
        run: docker-compose -f local.yml build

      - name: Run DB Migrations
        run: docker-compose -f local.yml run --rm django python manage.py migrate

      - name: Run Django Tests
        run: docker-compose -f local.yml run django pytest

      - name: Tear down the Stack
        run: docker-compose -f local.yml down

  frontend_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Setup yarn
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: |
            frontend/yarn.lock

      - name: Install modules
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Run tests
        run: yarn test
        working-directory: ./frontend

      - name: Build the test stack
        run: yarn build
        working-directory: ./frontend
