# name: Deploy to server

# on:
#   push:
#     branches:
#       - main
#     paths-ignore: ["docs/**"]

# concurrency:
#   group: ${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     environment:
#       name: name
#     steps:
#       - name: executing remote ssh commands using key
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_KEY }}
#           passphrase: ${{ secrets.SSH_PASSPHRASE }}
#           script: |
#             cd nejdejPy
#             git checkout main
#             git pull
#             docker-compose -f production.yml build
#             docker-compose -f production.yml up -d
